* bin/checkchroot: Convert to Perl, using Sbuild::Utility. * bin/chrapt: Convert to Perl, using Sbuild::Utility. * bin/chr-hold: Convert to Perl, using Sbuild::Utility. * bin/chr-unhold: Convert to Perl, using Sbuild::Utility. * bin/gochroot: Convert to Perl, using Sbuild::Utility. * bin/updatechroot:   - Convert to Perl, using Sbuild::Utility.   - chrapt is no longer used (Closes: #355035).   - Sbuild::Chroot is used for chroot access:     + Suite names are no longer hardcoded (Closes: #355037).     + APT Options are set correctly (Closes: #355038). * bin/upgradechroot: Convert to Perl, using Sbuild::Utility. * bin/common_functions: Remove; this is no longer used. * Sbuild/Utility.pm: New perl module for utility programs.  This is a   perl replacement for bin/common_functions. * debian/rules: Install Sbuild/Utility.pm into /usr/share/perl5/Sbuild.

diff --git a/bin/checkchroot b/bin/checkchroot
--- a/bin/checkchroot
+++ b/bin/checkchroot
@@ -1,32 +1,98 @@
-#!/bin/bash -e
+#!/usr/bin/perl -w
+# check the package list in a chroot against a reference list.
+#
+# Copyright (C) 2006 Roger Leigh <rleigh@debian.org>
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 
-# check the package list in a chroot against a reference.
+use strict;
+use warnings;
+use locale;
+use POSIX qw(locale_h);
+use Sbuild::Utility qw(setup cleanup);
 
-LC_COLLATE=POSIX
+package main;
 
-if [ $(id -u) != 0 ]; then
-	echo "You must be root to run this script, sorry."
-	exit 1
-fi
+sub usage {
+	print STDERR "Usage: $0 <chroot>\n";
+	exit 1;
+}
 
-USAGE_STRING="${0##*/} <chroot>"
-. /usr/share/sbuild/common_functions
-parse_arg $1
+usage() if (@ARGV != 1);
 
-tfile1="$(tempfile)"
-tfile2="$(tempfile)"
+setlocale(LC_COLLATE, "POSIX");
+$ENV{'LC_COLLATE'} = "POSIX";
 
-grep-status -F Status -s Package ' installed' "$CHROOT/var/lib/dpkg/status" | awk '{print $2}' | sort >"$tfile1"
+!setup($ARGV[0]) or die "Chroot setup failed";
+my $chroot_dir = $$Sbuild::Chroot::current{'Location'};
+my (@status, @ref, @install, @remove);
 
-sort "$CHROOT/../ref-$DIST" >"$tfile2"
+if (! open STATUS, "grep-status -F Status -s Package ' installed' '$chroot_dir/var/lib/dpkg/status' | awk '{print \$2}' |" ) {
+	print STDERR "Can't read dpkg status file in chroot: $!\n";
+	main::shutdown();
+}
+while (<STATUS>) {
+	chomp;
+	push @status, $_;
+}
+if (! close STATUS) {
+	print STDERR "Error reading dpkg status file in chroot: $!\n";
+	main::shutdown();
+}
 
-echo "DELETE             ADD"
-echo "============================"
-diff -u "$tfile1" "$tfile2" |
-	tail -n +3 |
-	grep ^[+-] |
-	sed -e 's/^-//' -e "s/^+/                   /" |
-	sort
+my $dist = Sbuild::Utility::get_dist($ARGV[0]);
 
-rm -f "$tfile1" "$tfile2"
+if (! open REF, "< $chroot_dir/../ref-$dist") {
+	print STDERR "Can't read reference status file $chroot_dir/../ref-$dist: $!\n";
+	main::shutdown();
+}
+while (<REF>) {
+	chomp;
+	push @ref, $_;
+}
+if (! close REF) {
+	print STDERR "Error reading reference status file: $!\n";
+	main::shutdown();
+}
 
+@status = sort @status;
+@ref = sort @ref;
+
+print "DELETE             ADD\n";
+print "======================================\n";
+my $i = 0;
+my $j = 0;
+
+while ($i < scalar @status || $j < scalar @ref) {
+
+	my $c = $status[$i] cmp $ref[$j];
+	if ($c < 0) {
+		# In status, not reference; remove.
+		print "$status[$i]\n";
+		$i++;
+	} elsif ($c > 0) {
+		# In reference, not status; install.
+		print "                   $ref[$j]\n";
+		$j++;
+	} else {
+		# Identical; skip.
+		$i++; $j++;
+	}
+}
+
+#ystem ("diff -u '$F1' '$F2' | tail -n +3 | grep ^[+-] | sed -e 's/^-//' -e 's/^+/                   /' | sort");
+
+cleanup();
+exit 0;
diff --git a/bin/chr-hold b/bin/chr-hold
--- a/bin/chr-hold
+++ b/bin/chr-hold
@@ -1,15 +1,63 @@
-#!/bin/bash
-
+#!/usr/bin/perl -w
 # changes the dpkg status of a package in a chroot to "hold"
+#
+# Copyright (C) 2006 Roger Leigh <rleigh@debian.org>
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 
-USAGE_STRING="${0##*/} <chroot> pkg1 [pkg2..]"
-. /usr/share/sbuild/common_functions
-parse_arg $1
-shift
+use strict;
+use warnings;
+use Sbuild::Utility qw(setup cleanup shutdown);
 
-for i in "$@" ; do
-	echo "$i        hold"
-done | sudo dpkg --root=$CHROOT --set-selections
+package main;
 
-dpkg --root=$CHROOT --list "$@"
+sub usage {
+	print STDERR "Usage: $0 <chroot> package [package ...]\n";
+	exit 1;
+}
 
+usage() if (@ARGV < 2);
+
+my $chroot = Sbuild::Utility::get_dist($ARGV[0]);
+
+!setup($ARGV[0]) or die "Chroot setup failed for $chroot chroot";
+
+print STDOUT "Holding packages in $chroot chroot:";
+
+my $command = get_command("$Sbuild::Conf::dpkg --set-selections", "root", 1);
+if (!open(SELECTIONS, "| $command")) {
+	print STDERR "Can't run dpkg --set-selections in chroot\n";
+	main::shutdown;
+}
+
+shift @ARGV;
+foreach (@ARGV) {
+	print SELECTIONS "$_        hold\n";
+	print STDOUT " $_";
+}
+
+if (!close SELECTIONS) {
+	print STDERR "Can't run dpkg --set-selections in chroot\n";
+	main::shutdown();
+}
+
+print STDOUT ".\n";
+
+my $packages = join(" ", @ARGV);
+my $status = run_command("$Sbuild::Conf::dpkg --list $packages", "root", 1, 0);
+
+cleanup();
+
+exit $status;
diff --git a/bin/chrapt b/bin/chrapt
--- a/bin/chrapt
+++ b/bin/chrapt
@@ -1,28 +1,50 @@
-#!/bin/bash
+#!/usr/bin/perl -w
+#
+# Copyright (C) 2006 Roger Leigh <rleigh@debian.org>
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 
-USAGE_STRING="${0##*/} <chroot> apt-get|apt-cache args"
-. /usr/share/sbuild/common_functions
-parse_arg $1
-shift
+use strict;
+use warnings;
+use Sbuild::Utility qw(setup cleanup);
 
-if [ $# -lt 2 ]; then usage; fi
+package main;
 
-# FHS change, potato -> woody
-if [ -d $CHROOT/var/lib/apt/lists ]; then
-	APTDIR=lib
-else
-	APTDIR=state
-fi
+sub usage {
+	print STDERR "Usage: $0 <chroot> apt-get|apt-cache args\n";
+	exit 1;
+}
 
-cmd=$1
-shift
-exec sudo $cmd \
-	-o Dir::State=$CHROOT/var/$APTDIR/apt \
-	-o Dir::State::status=$CHROOT/var/lib/dpkg/status \
-	-o Dir::Cache=$CHROOT/var/cache/apt \
-	-o Dir::Etc=$CHROOT/etc/apt \
-	-o Dir::Etc::main=$CHROOT/apt.conf \
-	-o Dir::Etc::parts=$CHROOT/apt.conf.d \
-	-o DPkg::Options::=--root=$CHROOT \
-	-o DPkg::Run-Directory=$CHROOT \
-	"$@"
+usage() if ($#ARGV < 2);
+
+my $command = $ARGV[1];
+if ($command eq "apt-get") {
+	$command = $Sbuild::Conf::apt_get;
+} elsif ($command eq "apt-cache") {
+	$command = $Sbuild::Conf::apt_cache;
+} else {
+	print STDERR "Bad command $command.  Allowed commands: apt-get or apt-cache\n";
+	exit 1;
+}
+
+!setup($ARGV[0]) or die "Chroot setup failed";
+
+shift @ARGV;
+shift @ARGV;
+my $cmd = join(' ', @ARGV);
+my $status = run_apt_command($command, $cmd, "root", 1);
+
+cleanup();
+exit $status;
diff --git a/bin/upgradechroot b/bin/upgradechroot
--- a/bin/upgradechroot
+++ b/bin/upgradechroot
@@ -1,15 +1,47 @@
-#!/bin/sh
+#!/usr/bin/perl -w
 #
+# Copyright (C) 2006 Roger Leigh <rleigh@debian.org>
+#
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
 
-DEFAULT_CHROOT="oldstable stable testing unstable"
-USAGE_STRING="${0##*/} <chroot> (default: $DEFAULT_CHROOT)"
+use strict;
+use warnings;
+use Sbuild::Utility qw(setup cleanup);
 
-. /usr/share/sbuild/common_functions
-CHROOTS=${*:-"$DEFAULT_CHROOT"}
+package main;
 
-for i in $CHROOTS; do
-	parse_arg $i
-	echo -e "\n   $i:"
-	chrapt $i apt-get -uy upgrade
-	#chrapt $i apt-get autoclean
-done
+sub usage {
+	print STDERR "Usage: $0 <chroot> [<chroot> ...]\n";
+	exit 1;
+}
+
+usage() if (@ARGV < 1);
+
+foreach (@ARGV) {
+
+	my $chroot = Sbuild::Utility::get_dist($_);
+
+	!setup($_) or die "Chroot setup failed for $chroot chroot";
+
+	print STDOUT "Upgrading $chroot chroot...\n";
+	my $status = run_apt_command($Sbuild::Conf::apt_get, "-uy upgrade",
+				     "root", 1);
+
+	cleanup();
+
+	exit $status if ($status);
+}
+
+exit 0;
