* bin/*: Reindent to increase readability. * chroot/*: Reindent to increase readability. * chroot/buildd.chroot: Add GPL boilerplate.

diff --git a/bin/dobuildlog b/bin/dobuildlog
--- a/bin/dobuildlog
+++ b/bin/dobuildlog
@@ -1,7 +1,6 @@
 #!/bin/bash -e
 #
 # vim:ts=4:noet:wrap:sts=4:sw=4:
-# $Id$
 # Rick Younie <rick@def.debian.net>
 #
 # craft a bug report or fail/success reply to a buildd log mail
@@ -20,13 +19,13 @@ FROM="$EMAIL"	# "Your Name <your@addr.ess>"
 ARCH=m68k		# for the bug report log link
 
 print_header () {
-	echo "From: $FROM"
-	sed -n '
+    echo "From: $FROM"
+    sed -n '
 		/^-----/,/^Automatic/ {
 			s/From: /To: /p
 			s/^Subject: Log/Subject: Re: Log/p
 		}'
-	echo
+    echo
 }
 
 fail_options () {
@@ -50,32 +49,32 @@ EOF
 }
 
 success_fail () {
-	STATUS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build .*/\1/p')
+    STATUS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build .*/\1/p')
 
-	case "$STATUS" in
-		successful )
-			print_header
-			sed -n '/\.changes:$/,$ {
+    case "$STATUS" in
+	successful )
+	    print_header
+	    sed -n '/\.changes:$/,$ {
 				/^Format: /,/^$/p
 			}' |$SIGNPRG 2>/dev/null
-			;;
-		failed )
-			print_header
-			fail_options
-			sed -n '/^Automatic build of/,$p'
-			;;
-		* )
-			echo "..this doesn't appear to be a buildd success/fail message"
-			exit 1
-			;;
-	esac
+	    ;;
+	failed )
+	    print_header
+	    fail_options
+	    sed -n '/^Automatic build of/,$p'
+	    ;;
+	* )
+	    echo "..this doesn't appear to be a buildd success/fail message"
+	    exit 1
+	    ;;
+    esac
 }
 
 bug_report () {
-	PKG=$1
-	VERS=$2
-	
-cat << EOF
+    PKG=$1
+    VERS=$2
+
+    cat << EOF
 From: $FROM
 To: submit@bugs.debian.org
 Subject: $PKG_VERS: fails to build
@@ -88,8 +87,9 @@ Hi,
 
 
 EOF
-sed -n '/^Automatic build of/,/^Build needed/ s/^/| /p'
-cat <<EOF
+
+    sed -n '/^Automatic build of/,/^Build needed/ s/^/| /p'
+    cat <<EOF
 
 
 The $ARCH build logs for $PKG can be found at
@@ -100,17 +100,17 @@ EOF
 }
 
 case "$1" in
-	gpg | agpg )
-		SIGNPRG="$1 $SIGNOPTS"
-		success_fail
-		exit 0
-		;;
-	bug )
-		PKG_VERS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build of \([^ ]*\) .*/\2/p')
-		bug_report $(echo "$PKG_VERS" |sed 's/_/ /')
-		;;
-	* )
-		echo "Usage: $(basename $0) gpg|agpg|bug"
-		exit 1
-		;;
+    gpg | agpg )
+	SIGNPRG="$1 $SIGNOPTS"
+	success_fail
+	exit 0
+	;;
+    bug )
+	PKG_VERS=$(sed -n '/^-----/,/^Automatic/ s/^Subject: Log for \([^ ]*\) build of \([^ ]*\) .*/\2/p')
+	bug_report $(echo "$PKG_VERS" |sed 's/_/ /')
+	;;
+    * )
+	echo "Usage: $(basename $0) gpg|agpg|bug"
+	exit 1
+	;;
 esac
