[sbuild-abort] Rewrite in perl
* Added --help and --version options
* Parse ps output robustly using perl regexes
* Kill sbuild process group

diff --git a/bin/sbuild-abort b/bin/sbuild-abort
--- a/bin/sbuild-abort
+++ b/bin/sbuild-abort
@@ -1,7 +1,9 @@
-#!/bin/bash
+#!/usr/bin/perl
 #
+# Abort the current build.
 # Copyright © 1998 Roman Hodek <Roman.Hodek@informatik.uni-erlangen.de>
 # Copyright © 2003 Ryan Murray <rmurray@debian.org>
+# Copyright © 2008 Roger Leigh <rleigh@debian.org>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -19,27 +21,55 @@
 #
 #######################################################################
 
-set -e
+use strict;
+use warnings;
 
-tmpfile=/tmp/abort-current-build.$$
-set +e
-ps xjww | egrep ' (/bin/sh /usr/bin/dpkg-buildpackage -us -uc |\(dpkg-buildpacka\))' >$tmpfile
-set -e
-n="`wc -l $tmpfile | awk '{print $1}'`"
-if [ "$n" -eq 0 ]; then
-    echo "No dpkg-buildpackage process found" 1>&2
-    rm -f $tmpfile
-    exit 1
-fi
-if [ "$n" -ge 2 ]; then
-    echo "More than one dpkg-buildpackage processes found:"
-    echo ' PPID   PID  PGID   SID TTY TPGID  STAT  UID   TIME COMMAND'
-    cat $tmpfile
-    rm -f $tmpfile
-    exit 1
-fi
-pgid=`awk '{print $3}' <$tmpfile`
-echo "Killing pgid $pgid"
-kill -15 -$pgid
-rm -f $tmpfile
-exit 0
+use Getopt::Long;
+use Sbuild qw(help_text version_text usage_error);
+
+GetOptions (
+    "h|help" => sub { help_text("1", "sbuild-abort"); },
+    "V|version" => sub {version_text("sbuild-abort"); })
+or usage_error("sbuild-abort", "Error parsing command-line options");
+
+my $buildcount = 0;
+my $linecount = 0;
+my $header = "";
+my @detail = ();
+
+open (PIPE, "/bin/ps xjww |") or die "Can't run /bin/ps: $!\n";
+while(<PIPE>) {
+    chomp;
+    if ($linecount == 0) {
+	$header = $_;
+    } elsif (m/\/usr\/bin\/perl \/usr\/bin\/dpkg-buildpackage/) {
+	push @detail, $_;
+	$buildcount++;
+    }
+    $linecount++;
+}
+close (PIPE) or die "Can't close /bin/ps pipe: $!\n";
+
+if ($buildcount == 0) {
+    print STDERR "E: No dpkg-buildpackage process found\n";
+    exit 1;
+} elsif ($buildcount > 1) {
+    print STDERR "E: More than one dpkg-buildpackage process found:\n";
+
+    print "I: $header\n";
+    foreach (@detail) {
+	print "I: $_\n";
+    }
+    exit 1;
+}
+
+# Get PGID from saved ps output.
+my @fields = split(/[[:space:]]+/, $detail[0]);
+die "Error parsing /bin/ps output" if (@fields < 1);
+my $pgid = $fields[2];
+
+# Kill process group.
+print "I: Killing process group $pgid\n";
+kill("TERM", -$pgid) or die "Error killing PGID $pgid: $!\n";
+
+exit 0;
